// <auto-generated />
using System;
using KeepItShort.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kepsi.Dal.Migrations
{
    [DbContext(typeof(KeepItShortContext))]
    [Migration("20231211131812_RemoveDBSet")]
    partial class RemoveDBSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KeepItShort.Persistance.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id");

                    b.ToTable("Emails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2023, 12, 11, 14, 18, 12, 84, DateTimeKind.Local).AddTicks(6078),
                            Content = "Temat: Zapytanie w Sprawie Mojej Aktualnej Sytuacji  Do firmy windykacyjnej,  Nazywam się Jan Kowalski i chciałbym uzyskać aktualne informacje dotyczące mojej sprawy windykacyjnej. Ostatnio otrzymałem kilka pism od Waszej firmy, ale potrzebuję więcej szczegółów na temat postępu w mojej sprawie.  Proszę o udzielenie odpowiedzi na następujące pytania:  Jaka jest aktualna kwota mojego zadłużenia? Czy są jakieś dodatkowe opłaty lub koszty, o których powinienem wiedzieć? Jakie kroki podejmujecie w związku z moją sprawą i jakie są kolejne etapy procesu? Rozumiem, że obowiązek spłaty długu spoczywa na mnie, ale chciałbym lepiej zrozumieć, w jakim punkcie znajduje się obecnie ta sprawa i jakie są moje opcje.  Proszę o udzielenie jasnych informacji, które pomogą mi lepiej zrozumieć sytuację.  Z góry dziękuję za odpowiedź.  Z poważaniem,  Jan Kowalski 111 222 333 jk@test.com",
                            ConversationId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2023, 12, 11, 14, 18, 12, 84, DateTimeKind.Local).AddTicks(6126),
                            Content = "Temat: Hmmm... Sprawa Jakaś Tam  Cześć Janek,  No witaj! Okej, coś tam sprawdziliśmy i tak... masz jakiś dług u nas. Trochę tu, trochę tam, ale ogólnie luz. Nie przejmuj się, to tylko formalność. Na pewno szybko to ogarniemy.  Co do szczegółów, no wiesz, nie bierz tego tak na poważnie. Dług to dług, ale przecież każdy ma jakieś rachunki do spłacenia, nie? Trochę zabawy z dokumentami, kilka telefonów, i już będzie po sprawie. To nic takiego.  Jakieś pytania? Ech, szkoda nerwów! Po co te wszystkie detale? Wszystko się poukłada, a do tego czasu... no cóż, życie.  Piona, Adaś Kruk 222 333 444 adas@buziaczek.pl",
                            ConversationId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2023, 12, 11, 14, 18, 12, 84, DateTimeKind.Local).AddTicks(6156),
                            Content = "Temat: Zgłoszenie Sprawy do Pracodawcy  Dzień dobry,  Chciałem wyrazić swoje rozczarowanie w związku z tonem i treścią Pańskiego ostatniego maila. Mam wrażenie, że nie zrozumiał Pan powagi mojej sytuacji finansowej i sposób, w jaki zostałem potraktowany, nie przystaje do standardów profesjonalizmu.  Rozumiem, że wszyscy mamy swoje obowiązki, ale oczekuję jednak pewnego szacunku w trakcie komunikacji, szczególnie w kontekście spraw finansowych. Wasza reakcja wydaje mi się mało profesjonalna.  Informuję, że zrzekam się dalszej korespondencji mailowej i zgłaszam tę sytuację do Państwa pracodawcy. Uważam, że taka forma komunikacji nie jest akceptowalna i mam nadzieję, że zostanie to wzięte pod uwagę w kontekście szkoleń dotyczących obsługi klienta.  Czekam na informację zwrotną w tej sprawie.  Z poważaniem,  Jan Kowalski 111 222 333 jk@test.com",
                            ConversationId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2023, 12, 11, 14, 18, 12, 84, DateTimeKind.Local).AddTicks(6165),
                            Content = "Temat: Zgłoszenie Sprawy do Pracodawcy  Dzień dobry,  Chciałem wyrazić swoje rozczarowanie w związku z tonem i treścią Pańskiego ostatniego maila. Mam wrażenie, że nie zrozumiał Pan powagi mojej sytuacji finansowej i sposób, w jaki zostałem potraktowany, nie przystaje do standardów profesjonalizmu.  Rozumiem, że wszyscy mamy swoje obowiązki, ale oczekuję jednak pewnego szacunku w trakcie komunikacji, szczególnie w kontekście spraw finansowych. Wasza reakcja wydaje mi się mało profesjonalna.  Informuję, że zrzekam się dalszej korespondencji mailowej i zgłaszam tę sytuację do Państwa pracodawcy. Uważam, że taka forma komunikacji nie jest akceptowalna i mam nadzieję, że zostanie to wzięte pod uwagę w kontekście szkoleń dotyczących obsługi klienta.  Czekam na informację zwrotną w tej sprawie.  Z poważaniem,  Adam Nowak 222 333 444 anowak@kruk.pl",
                            ConversationId = 1
                        });
                });

            modelBuilder.Entity("KeepItShort.Persistance.Models.RefactoredEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RefactoredConversationId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("RefactoredConversationId");

                    b.ToTable("RefactoredEmail");
                });

            modelBuilder.Entity("Kepsi.Dal.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RefactoredConversationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RefactoredConversationId = 0
                        },
                        new
                        {
                            Id = 2,
                            RefactoredConversationId = 0
                        },
                        new
                        {
                            Id = 3,
                            RefactoredConversationId = 0
                        },
                        new
                        {
                            Id = 4,
                            RefactoredConversationId = 0
                        },
                        new
                        {
                            Id = 5,
                            RefactoredConversationId = 0
                        });
                });

            modelBuilder.Entity("Kepsi.Dal.Models.RefactoredConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.ToTable("RefactoredConversation");
                });

            modelBuilder.Entity("KeepItShort.Persistance.Models.Email", b =>
                {
                    b.HasOne("Kepsi.Dal.Models.Conversation", "Conversation")
                        .WithMany("Emails")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("KeepItShort.Persistance.Models.RefactoredEmail", b =>
                {
                    b.HasOne("KeepItShort.Persistance.Models.Email", "EmailRef")
                        .WithOne("RefactoredEmailRef")
                        .HasForeignKey("KeepItShort.Persistance.Models.RefactoredEmail", "EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kepsi.Dal.Models.RefactoredConversation", "RefactoredConversationRef")
                        .WithMany("RefactoredEmails")
                        .HasForeignKey("RefactoredConversationId");

                    b.Navigation("EmailRef");

                    b.Navigation("RefactoredConversationRef");
                });

            modelBuilder.Entity("Kepsi.Dal.Models.RefactoredConversation", b =>
                {
                    b.HasOne("Kepsi.Dal.Models.Conversation", "ConversationRef")
                        .WithOne("RefactoredConversationRef")
                        .HasForeignKey("Kepsi.Dal.Models.RefactoredConversation", "ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationRef");
                });

            modelBuilder.Entity("KeepItShort.Persistance.Models.Email", b =>
                {
                    b.Navigation("RefactoredEmailRef");
                });

            modelBuilder.Entity("Kepsi.Dal.Models.Conversation", b =>
                {
                    b.Navigation("Emails");

                    b.Navigation("RefactoredConversationRef");
                });

            modelBuilder.Entity("Kepsi.Dal.Models.RefactoredConversation", b =>
                {
                    b.Navigation("RefactoredEmails");
                });
#pragma warning restore 612, 618
        }
    }
}
